name: Build and Deploy Prod

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ['self-hosted','X64']
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-3
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Build the Docker image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build --file Dockerfile -t $ECR_REGISTRY/php-gateway-bsre-sign:latest .

    - name: Push Docker Image to ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker push $ECR_REGISTRY/php-gateway-bsre-sign:latest

    # - name: Update ECS Deployment
    #   run: |
    #     aws ecs update-service --cluster cluster-core-prod --service superapp-print-service --force-new-deployment
